[package]
name = "hola"
version = "0.1.0"
authors = ["Dan Ortega <ortega.dan2010@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
